### ISSUE TITLE
new 2.1 API causes SSL error 

### ISSUE THREAD

**Issue by egonw** [egonw/ops4j#8]
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:126)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:437)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.github.egonw.ops4j.AbstractOPS4JClient.runRequest(AbstractOPS4JClient.java:83)
	at com.github.egonw.ops4j.ActivityTypes.list(ActivityTypes.java:65)
	at com.github.egonw.ops4j.ActivityTypesTest.list(ActivityTypesTest.java:50)

**Comment by egonw** [comment]
See also http://support.openphacts.org/support/tickets/164

**Comment by egonw** [comment]
Fixed upstream.
